/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autoquest;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import javax.swing.Timer;
import autoquest.NarrativeDust;
import java.util.Random;

/**
 *
 * @author ncc
 */
public class MainWindow extends javax.swing.JFrame implements ActionListener {
    
    private int level;
    private CharacterSheet characterSheet;
    private DefaultListModel characterSheetModel = new DefaultListModel();
    private boolean intro = true;
    private Timer mainLoop = new Timer(100, this);
    private DefaultListModel mobList = new DefaultListModel();
    private DefaultListModel inventoryList = new DefaultListModel();
    private String currentMob;
    private ItemList item = new ItemList();
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        mainLoop.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        characterSheetList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        narrativeProgressBar = new javax.swing.JProgressBar();
        nameLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        narrativeField = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        levelLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        mobListView = new javax.swing.JList<>();
        killingProgressBar = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        johnCheckbox = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        sortMobListButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Character Sheet");

        characterSheetList.setModel(characterSheetModel);
        characterSheetList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(characterSheetList);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Inventory");

        jList2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jList2ComponentAdded(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        nameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        nameLabel.setText("Name");

        narrativeField.setEditable(false);
        narrativeField.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(narrativeField);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Equipment");

        jScrollPane4.setViewportView(jList3);

        levelLabel.setText("Level: 0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Killing Queue");

        mobListView.setModel(mobList);
        jScrollPane5.setViewportView(mobListView);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Gameplay Options");

        jCheckBox2.setLabel("DLC Content");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        johnCheckbox.setSelected(true);
        johnCheckbox.setLabel("John O'Connor");
        johnCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                johnCheckboxActionPerformed(evt);
            }
        });

        jCheckBox4.setText("HD Remix");

        jButton1.setText("Sort Inventory (randomly)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sortMobListButton.setText("Sort Monsters (bubble)");
        sortMobListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortMobListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(narrativeProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(levelLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(175, 175, 175)
                                .addComponent(jLabel1)
                                .addGap(102, 102, 102)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(killingProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(johnCheckbox)
                                            .addComponent(jCheckBox4)
                                            .addComponent(jLabel7)
                                            .addComponent(jCheckBox2)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(sortMobListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(levelLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(narrativeProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jLabel6))
                    .addComponent(killingProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sortMobListButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(johnCheckbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox4))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        levelLabel.getAccessibleContext().setAccessibleName("Current Level: 0");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent e) {
        // Intro sequence
        if (intro) {
            narrativeProgressBar.setValue(narrativeProgressBar.getValue() + 1);
            if (narrativeProgressBar.getValue() <= 30) {
                this.narrativeField.setText("You awake in a darkened forest in the middle of nowhere.");
                return;
            } else if (narrativeProgressBar.getValue() <= 50) {
                this.narrativeField.setText("You have nothing but the clothes on your back and your fists.");
                return;
            } else if (narrativeProgressBar.getValue() <= 60) {
                this.narrativeField.setText("You are cold.");
                return;
            } else if (narrativeProgressBar.getValue() <= 70) {
                this.narrativeField.setText("You are alone.");
                return;
            } else if (narrativeProgressBar.getValue() <= 90) {
                this.narrativeField.setText("With your remaining strength, you pick yourself up and venture into the forest");
                return;
            } else if (narrativeProgressBar.getValue() < 100){
                this.narrativeField.setText("This is your story.");
                return;
            } else {
                intro = false;
                narrativeProgressBar.setValue(0);
                mainLoop.setDelay(250);
                setLevel(1);
                return;
            }
        }
        
        // Main game loop
        if (narrativeProgressBar.getValue() == 1) {
            this.narrativeField.setText(NarrativeDust.motivationGenerator() + QuestList.fetchQuest());
        } else if (narrativeProgressBar.getValue() == 10) {
            this.narrativeField.setText("Monsters surround you as you begin your quest. You must fight to survive");
            Random random = new Random();
            
            for (int i = 0; i < 18; i++) {
                if (johnCheckbox.isSelected()) {
                    if (i == 0) mobList.addElement("THE REAL John O'Connor");
                    mobList.addElement("John O'Connor");
                }
            }
        } else if (narrativeProgressBar.getValue() < 15) {
        } else if (narrativeProgressBar.getValue() >= 15 && narrativeProgressBar.getValue() <= 99) {
            if (killingProgressBar.getValue() == 0) {
                currentMob = (String)mobList.get(0);
                narrativeField.setText("Now battling " + currentMob + ". " + NarrativeDust.difficultyGenerator());
                
            }
            if (killingProgressBar.getValue() != 100) {
                killingProgressBar.setValue(killingProgressBar.getValue() + 1);
                return;
            } else {
                mobList.remove(0);
                killingProgressBar.setValue(0);
                narrativeProgressBar.setValue(narrativeProgressBar.getValue() + 5);
                inventoryList.addElement(item.dropItem());
            }
        } else {
            narrativeProgressBar.setValue(0);
            setLevel(level + 1);
        }
        narrativeProgressBar.setValue(narrativeProgressBar.getValue() + 1);
    }
    
    private void setLevel(int level) {
        this.level = level;
        this.levelLabel.setText("Level: " + String.valueOf(level));
    }
    
    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void johnCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_johnCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_johnCheckboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sortMobListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortMobListButtonActionPerformed
        boolean sorted;
        do {
            sorted = true;
            for (int i = 0; i < mobList.size() - 1; i += 1) {
                if (((String)mobList.get(i)).compareTo((String)mobList.get(i + 1)) < 0) {
                    Object tmp = mobList.get(i);
                    mobList.set(i, mobList.get(i + 1));
                    mobList.set(i + 1, tmp);
                    sorted = false;
                }
            }
        } while (!sorted);
    }//GEN-LAST:event_sortMobListButtonActionPerformed

    private void jList2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jList2ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jList2ComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainWindow window = new MainWindow();
                window.setVisible(true);
                window.mainLoop.start();
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> characterSheetList;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox johnCheckbox;
    private javax.swing.JProgressBar killingProgressBar;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JList<String> mobListView;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextPane narrativeField;
    private javax.swing.JProgressBar narrativeProgressBar;
    private javax.swing.JButton sortMobListButton;
    // End of variables declaration//GEN-END:variables

    public void setCharacterSheet(CharacterSheet sheet) {
        this.characterSheet = sheet;
        characterSheetModel.addElement("STR: " + sheet.getStr());
        characterSheetModel.addElement("CON: " + sheet.getCon());
        characterSheetModel.addElement("DEX: " + sheet.getDex());
        characterSheetModel.addElement("INT: " + sheet.getInt());
        nameLabel.setText(sheet.getName());
    }
}
